name: Shell script lints

on: [push, pull_request]

jobs:
  lints:
    runs-on: ubuntu-latest
    name: lints
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Install lint dependencies
        run: sudo apt-get install -y shellcheck checkbashisms
      - name: shellcheck lints of shell script source
        run: make shellcheck
      - name: checkbashisms lints of shell script source
        run: make checkbashisms
